### PR TITLE
Login Back End

### PR DESCRIPTION
**Pull request by mohammedelbachiri**
Login Back End

### CODE REVIEW

**Review by Benfill — CHANGES_REQUESTED** [review]
Desktop-screenshot-10-09-2024_08_05_PM
Desktop-screenshot-10-09-2024_08_07_PM
There is small issues should be fixed

**Comment by mohammedelbachiri** [comment]
we should choose one of this ways to name the User(entity) props/getters/setters  (example: first name): 

1.
    private String first_name; 

2.
 @Column(name = "first_name")
    private String firstName;
    
     // so the user table have column named "first_name"

**Comment by Benfill** [comment]
the javabeans who's responsible for displaying attribute in jsp doesnt allow Snake case: first_name
so we should work with the second one
@column(name = "first_name")
private String firstName;

**Comment by Benfill** [comment]
so we should work with the second one
@column(name = "first_name")
private String firstName;

**Pull request merged**
